grocery/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

index = lambda request: render(request, 'index.html')

urlpatterns = [
    path('', index, name='index'),
    path('items/', include('items.urls')),
    path('categories/', include('categories.urls')),
    path('admin/', admin.site.urls),
]

items/urls.py
from django.urls import path
from . import views


app_name = 'items'

urlpatterns = [
    path('', views.items_home, name='home'),
    path('new', views.ItemCreateView.as_view(), name='create'),
    path('item-list', views.item_list, name='item-list'),
    path('<int:pk>', views.item, name='item'),
    path('<int:pk>/update', views.ItemUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.ItemDeleteView.as_view(), name='delete'),
]

items/models.py
from django.db import models
from simple_history.models import HistoricalRecords


class Item(models.Model):
    name = models.CharField(max_length=100, unique=True)
    history = HistoricalRecords()
    
    
    def __str__(self):
        return self.name
    
    
    @property
    def category_list(self):
        categoires = self.categories.all()
        if categoires.exists():
            return ', '.join([category.name for category in categoires])
        return 'None'

items/forms.py
from django import forms

from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout

from .models import  Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(FloatingField('name'))

items/views.py
from django.shortcuts import render

from htmx_modal_forms.views import HTMXModalCreateView, HTMXModalUpdateView, HTMXModalDeleteView

from .forms import ItemForm
from .models import  Item


items_home = lambda request: render(request, 'items/index.html')

item = lambda request, pk: render(request, 'items/index.html#item', {'item': Item.objects.get(id=pk)})

item_list = lambda request: render(request, 'items/index.html#item-list', {'items': Item.objects.order_by('name')})


class ItemCreateView(HTMXModalCreateView):
    model = Item
    template_name = 'items/index.html#item-form'
    form_class = ItemForm


class ItemUpdateView(HTMXModalUpdateView):
    model = Item
    template_name = 'items/index.html#item-form'
    form_class = ItemForm


class ItemDeleteView(HTMXModalDeleteView):
    model = Item
    template_name = 'items/index.html#item-form'

items/templates/items/index.html
{% extends 'base.html' %}
{% load partials %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Item List{% endblock %}

{% startpartial item %}
<div>{{ item }} ({{ item.category_list }})</div>
<div>
  <button hx-get="{% url 'items:update' item.id %}" hx-target="#dialog" class="btn btn-sm btn-primary">
    Edit
  </button>
  <button hx-get="{% url 'items:delete' item.id %}" hx-target="#dialog" class="btn btn-sm btn-danger">
    Delete
  </button>
</div>
{% endpartial %}

{% startpartial item-list %}
  {% for item in items %}
  <!-- Item -->
  <li id="item-{{ item.id }}" hx-trigger="item-{{ item.id }}-updated from:body" hx-get="{% url 'items:item' item.id %}" hx-target="this" class="list-group-item d-flex justify-content-between">
    <div>{{ item }} ({{ item.category_list }})</div>
    <div>
      <button hx-get="{% url 'items:update' item.id %}" hx-target="#dialog" class="btn btn-sm btn-primary">
        Edit
      </button>
      <button hx-get="{% url 'items:delete' item.id %}" hx-target="#dialog" class="btn btn-sm btn-danger">
        Delete
      </button>
    </div>
  </li>
  {% endfor %}
{% endpartial %}

{% startpartial item-form %}
<form hx-post="{{ url }}">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">{{ form_title }}</h5>
    </div>
    <div class="modal-body">
      {% crispy form %}
      {{ form_body }}
    </div>
    <div class="modal-footer">
      <button type="button" data-bs-dismiss="modal" class="btn btn-secondary">Cancel</button>
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </div>
</form>
{% endpartial %}

{% block body %}
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1 class="mb-0">Items</h1>
  <button hx-get="{% url 'items:create' %}" hx-target="#dialog" class="btn btn-primary">
    +
  </button>
</div>

<!-- Item List -->
<ul hx-trigger="load, item-created from:body, item-deleted from:body" hx-get="{% url 'items:item-list' %}" hx-target="this" class="list-group list-group-flush"></ul>

<!-- Modal Form -->
<div id="modal" class="modal fade">
  <div id="dialog" class="modal-dialog" hx-target="this"></div>
</div>
{% endblock %}

{% block footer %}
<script src="{% static 'htmx_modal_forms/script.js' %}"></script>
{% endblock %}