categories/urls.py
from django.urls import path
from . import views


app_name = 'categories'

urlpatterns = [
    path('', views.categories_home, name='home'),
    path('new', views.CategoryCreateView.as_view(), name='create'),
    path('category-list', views.category_list, name='category-list'),
    path('<int:pk>', views.category, name='category'),
    path('<int:pk>/update', views.CategoryUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.CategoryDeleteView.as_view(), name='delete'),
]

grocery/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

index = lambda request: render(request, 'index.html')

urlpatterns = [
    path('', index, name='index'),
    path('items/', include('items.urls')),
    path('categories/', include('categories.urls')),
    path('admin/', admin.site.urls),
]

items/urls.py
from django.urls import path
from . import views


app_name = 'items'

urlpatterns = [
    path('', views.items_home, name='home'),
    path('new', views.ItemCreateView.as_view(), name='create'),
    path('item-list', views.item_list, name='item-list'),
    path('<int:pk>', views.item, name='item'),
    path('<int:pk>/update', views.ItemUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.ItemDeleteView.as_view(), name='delete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <script src="https://unpkg.com/htmx.org@1.9.5"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block head %}{% endblock %}
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  {% for message in messages %}{{ message }}{% endfor %}
  <nav class="navbar navbar-expand-sm bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" class="navbar-brand" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'items:home' %}">Items</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'categories:home' %}">Categories</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <main class="container mt-3">
    {% block body %}{% endblock %}
  </main>

  <footer>
    <!-- Boostrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <!-- HTMX Messages -->
    {% include 'htmx_messages/toast.html' %}
    <script src="{% static 'htmx_messages/toasts.js' %}"></script>
    {% block footer %}{% endblock %}
  </footer>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Index{% endblock %}