categories/urls.py
from django.urls import path
from . import views


app_name = 'categories'

urlpatterns = [
    path('', views.categories_home, name='home'),
    path('new', views.CategoryCreateView.as_view(), name='create'),
    path('category-list', views.category_list, name='category-list'),
    path('<int:pk>', views.category, name='category'),
    path('<int:pk>/update', views.CategoryUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.CategoryDeleteView.as_view(), name='delete'),
]

grocery/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include

index = lambda request: render(request, 'index.html')

urlpatterns = [
    path('', index, name='index'),
    path('items/', include('items.urls')),
    path('categories/', include('categories.urls')),
    path('admin/', admin.site.urls),
]

items/urls.py
from django.urls import path
from . import views


app_name = 'items'

urlpatterns = [
    path('', views.items_home, name='home'),
    path('new', views.ItemCreateView.as_view(), name='create'),
    path('item-list', views.item_list, name='item-list'),
    path('<int:pk>', views.item, name='item'),
    path('<int:pk>/update', views.ItemUpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.ItemDeleteView.as_view(), name='delete'),
]

categories/models.py
from django.db import models

from simple_history.models import HistoricalRecords

from items.models import Item


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    items = models.ManyToManyField(Item, related_name='categories', blank=True)
    history = HistoricalRecords()
    
    
    def __str__(self):
        return self.name

    
    @property
    def item_list(self):
        if self.items.exists():
            return ', '.join([item.name for item in self.items.order_by('name')])
        return 'None'

categories/forms.py
from django import forms

from crispy_bootstrap5.bootstrap5 import FloatingField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout

from items.models import Item

from .models import Category


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'items': forms.widgets.CheckboxSelectMultiple(),
        }
    
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            FloatingField('name'),
            'items',
        )

categories/views.py
from django.shortcuts import render

from htmx_modal_forms.views import HTMXModalCreateView, HTMXModalUpdateView, HTMXModalDeleteView

from .forms import CategoryForm
from .models import  Category


categories_home = lambda request: render(request, 'categories/index.html')

category = lambda request, pk: render(request, 'categories/index.html#category', {'category': Category.objects.get(id=pk)})

category_list = lambda request: render(request, 'categories/index.html#category-list', {'categories': Category.objects.order_by('name')})


class CategoryCreateView(HTMXModalCreateView):
    model = Category
    template_name = 'categories/index.html#category-form'
    form_class = CategoryForm
    url_name = 'categories:create'


class CategoryUpdateView(HTMXModalUpdateView):
    model = Category
    template_name = 'categories/index.html#category-form'
    form_class = CategoryForm
    url_name = 'categories:update'


class CategoryDeleteView(HTMXModalDeleteView):
    model = Category
    template_name = 'categories/index.html#category-form'
    url_name = 'categories:delete'

categories/templates/categories/index.html
{% extends 'base.html' %}
{% load partials %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Category List{% endblock %}

{% startpartial category %}
<div>{{ category }} ({{ category.item_list }})</div>
<div>
  <button hx-get="{% url 'categories:update' category.id %}" hx-target="#dialog" class="btn btn-sm btn-primary">
    Edit
  </button>
  <button hx-get="{% url 'categories:delete' category.id %}" hx-target="#dialog" class="btn btn-sm btn-danger">
    Delete
  </button>
</div>
{% endpartial %}

{% startpartial category-list %}
  {% for category in categories %}
  <!-- Category -->
  <li id="category-{{ category.id }}" hx-trigger="category-{{ category.id }}-updated from:body" hx-get="{% url 'categories:category' category.id %}" hx-target="this" class="list-group-item d-flex justify-content-between">
    <div>{{ category }} ({{ category.item_list }})</div>
    <div>
      <button hx-get="{% url 'categories:update' category.id %}" hx-target="#dialog" class="btn btn-sm btn-primary">
        Edit
      </button>
      <button hx-get="{% url 'categories:delete' category.id %}" hx-target="#dialog" class="btn btn-sm btn-danger">
        Delete
      </button>
    </div>
  </li>
  {% endfor %}
{% endpartial %}

{% startpartial category-form %}
<form hx-post="{{ url }}">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">{{ form_title }}</h5>
    </div>
    <div class="modal-body">
      {% crispy form %}
      {{ form_body }}
    </div>
    <div class="modal-footer">
      <button type="button" data-bs-dismiss="modal" class="btn btn-secondary">Cancel</button>
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </div>
</form>
{% endpartial %}

{% block body %}
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1 class="mb-0">Categories</h1>
  <button hx-get="{% url 'categories:create' %}" hx-target="#dialog" class="btn btn-primary">
    +
  </button>
</div>

<!-- Category List -->
<ul hx-trigger="load, category-created from:body, category-deleted from:body" hx-get="{% url 'categories:category-list' %}" hx-target="this" class="list-group list-group-flush"></ul>

<!-- Modal Form -->
<div id="modal" class="modal fade">
  <div id="dialog" class="modal-dialog" hx-target="this"></div>
</div>
{% endblock %}

{% block footer %}
<script src="{% static 'htmx_modal_forms/script.js' %}"></script>
{% endblock %}